spring:
  datasource:
    #url: jdbc:oracle:thin:@192.168.0.159:1521:daqsoftFramework
    url: jdbc:mysql://192.168.2.67:3306/jpatest
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver